version: "3"

services:
  nuxt:
    build:
      context: '../'
      dockerfile: 'DockerFile'
    container_name: tierlist-maker
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
